from omegaconf import OmegaConf

config = {
  'general': {
    'experiment_name': 'DNN tuning',
    'seed': 31415,
    'num_classes': 1,
  },
  'paths': {
    'path_to_train_data': './data/train.csv',
    'path_to_test_data': './data/test.csv',
    'path_to_checkpoints': './checkpoints',
    'path_to_logs': './logs/${general.experiment_name}.txt',
    'path_to_submission': './submission.csv',
  },
  'data': {
    'target_col': 'SalePrice',
    'transform_target': True,
    'id_col': 'Id',
  },
  'cv': {
    'n_splits': 5,
    'shuffle': True,
    'random_state': '${general.seed}',
  },
  'fit': {
    'val_size': 0.2,
  },
  'models_params': {
    'regression': {},
    'ridge': {
      'alpha': 10,
    },
    'lasso': {
      'alpha': 0.001,
    },
    'elasticnet': {
      'alpha': 0.001,
      'l1_ratio': 0.5,
      'max_iter': 400,
      'selection': 'random',
    },
    'KNN': {
      'weights': 'distance',
      'p': 1,
      'leaf_size': 20,
      'n_neighbors': 5,
    },
    'decision_tree': {
      'max_depth': 20,
      'max_features': 0.5,
      'min_samples_leaf': 10,
      'min_samples_split': 10,
    },
    'random_forest': {
      'n_estimators': 300,
      'min_samples_split': 2,
      'min_samples_leaf': 1,
      'max_features': 0.5,
      'max_depth': None,
    },
    'catboost': {
      'subsample': 0.7,
      'random_strength': 3,
      'min_data_in_leaf': 20,
      'learning_rate': 0.03,
      'l2_leaf_reg': 1,
      'iterations': 1000,
      'depth': 5,
      'colsample_bylevel': 0.6,
      'verbose': False,
      'allow_writing_files': False,
    },
    'lightgbm': {
      'subsample': 0.8,
      'reg_lambda': 1.0,
      'reg_alpha': 0.0,
      'num_leaves': 31,
      'n_estimators': 1200,
      'min_child_samples': 5,
      'max_depth': 12,
      'learning_rate': 0.03,
      'colsample_bytree': 0.6,
      'force_col_wise': True,
      'verbose': -1,
    },
    'xgboost': {
      'subsample': 0.7,
      'reg_lambda': 1.0,
      'reg_alpha': 0.1,
      'n_estimators': 800,
      'min_child_weight': 3,
      'max_depth': 4,
      'learning_rate': 0.05,
      'gamma': 0.0,
      'colsample_bytree': 0.6,
      'verbosity': 0,
      'n_jobs': 1,
    },
    'ensemble': {
      'type': 'stacking',
      'models': {
        'regression': 0,
        'ridge': 0,
        'lasso': 0,
        'elasticnet': 0,
        'KNN': 0,
        'decision_tree': 0,
        'random_forest': 0,
        'catboost': 1,
        'lightgbm': 1,
        'xgboost': 1,
      },
    },
    'DNN': {
      'hidden_dims': [128, 64],
      'dropout': 0.1,
      'lr': 0.02,
      'batch_size': 32,
      'num_epochs': 200,
      'patience': 30,
      'weight_decay': 0.01,
      'device': 'auto',
      'batch_norm': True,
    },
  },
  'training_model': 'DNN',
  'need_scaler': True,
  'mode': 'train',
  'rerun': True,
  'logging': True,
  'save_best_model': True,
  'save_last_model': True,
  'model_type': 'regression',
  'metric': 'neg_mean_squared_log_error',
  'is_negative_metric': True,
}

config = OmegaConf.create(config)
